version: "3.7"
services: 
  db:
    image: mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks: 
      - backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node-container
    volumes:
      - ./api:/home/node/app
    ports: 
      - "9001:9001"
    restart: always
    networks:
      - backend
  web:
    image: "php:7.2-apache"
    container_name: php-container
    working_dir: "/var/www/html"
    volumes:
      - ./website:/var/www/html
    ports: 
      - "8888:80"
    restart: always
    networks: 
      - backend

networks:
  backend:
    driver: "bridge"